name: Train Random Forest Model
description: Train a Random Forest model using features CSV and save the model
inputs:
  - {name: features_csv, type: Csv}
  - {name: label_column, type: String}
  - {name: model_output, type: String}
outputs:
  - {name: model_file, type: Model}
implementation:
  container:
    image: python:3.9
    command:
      - sh
      - -c
      - |
        pip install --quiet pandas scikit-learn joblib && \
        python3 train_model.py \
          --features_csv {inputPath: features_csv} \
          --label_column {inputValue: label_column} \
          --model_output {outputPath: model_file}
